function [TF] = stfg_get_TF(stfg,stim)

% [TF] = STFG_GET_TF(STFG,STIM) - 
%
% INPUTS: 
%       STFG -
%       STIM - 'TF!', 'TF2', 'TF3', or 'TF4'
%
% OUTPUTS: 
%       TF - structure containing average response to pref and null
%       directions (across animals) and stats.
%
% NOTES: 
% - add DR stuff here too


[TF.pref_all, ...
    TF.pref_avg, ...
    TF.pref_ste, ...
    TF.null_all, ...
    TF.null_avg, ...
    TF.null_ste] = stfg_get_prefnull(stfg,stim);

[TF.mmm_all, ...
    TF.mmm_avg, ...
    TF.mmm_ste, ...
    TF.dir2_all, ...
    TF.dir2_avg, ...
    TF.dir2_ste] = stfg_get_alldir(stfg,stim);

[TF.bs_mmm_all, ...
    TF.bs_mmm_avg, ...
    TF.bs_mmm_ste, ...
    TF.bs_dir2_all, ...
    TF.bs_dir2_avg, ...
    TF.bs_dir2_ste] = stfg_bs_get_alldir(stfg,stim);