function [TF] = stfe_get_TF(stiminfo,pvalue)

%
%
%
%
%
%
%
%
%
%


[TF.pref_all, ...
    TF.pref_avg, ...
    TF.pref_ste, ...
    TF.null_all, ...
    TF.null_avg, ...
    TF.null_ste] = stfe_get_prefnull(stiminfo,pvalue);

TF.numcells = length(find(~isnan(TF.pref_all(:,1))));

[TF.mmm_all, ...
    TF.mmm_avg, ...
    TF.mmm_ste, ...
    TF.dir2_all, ...
    TF.dir2_avg, ...
    TF.dir2_ste] = stfe_get_alldir(stiminfo,pvalue);

[TF.bs_mmm_all, ...
    TF.bs_mmm_avg, ...
    TF.bs_mmm_ste, ...
    TF.bs_dir2_all, ...
    TF.bs_dir2_avg, ...
    TF.bs_dir2_ste] = stfe_bs_get_alldir(stiminfo,pvalue);
